# Generated by Django 3.0.3 on 2020-03-29 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekinoback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
