# Generated by Django 3.0.3 on 2020-03-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekinoback', '0002_auto_20200329_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='place_id',
            field=models.CharField(max_length=255, verbose_name='Код кінотеатру в Google API'),
        ),
    ]
