# Generated by Django 3.0.3 on 2020-03-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekinoback', '0003_auto_20200330_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, to='ekinoback.Actor', verbose_name='Актори'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='studio',
            field=models.ManyToManyField(blank=True, to='ekinoback.Studio', verbose_name='Студія'),
        ),
    ]
