# Generated by Django 3.0.3 on 2020-03-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekinoback', '0004_auto_20200331_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='phone',
            field=models.CharField(blank=True, max_length=17, verbose_name='Мобільний номер'),
        ),
    ]
